# Generated by Django 5.2 on 2026-05-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['data_hora'], name='idx_registro_data_hora'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['tipo'], name='idx_registro_tipo'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['veiculo', 'tipo'], name='idx_registro_veiculo_tipo'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['placa'], name='idx_veiculo_placa'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['proprietario'], name='idx_veiculo_proprietario'),
        ),
    ]
